# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dcm_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DCMInterface(object):
    def setupUi(self, DCMInterface):
        DCMInterface.setObjectName("DCMInterface")
        DCMInterface.resize(943, 642)
        self.centralwidget = QtWidgets.QWidget(DCMInterface)
        self.centralwidget.setStyleSheet("QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 8px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
" QScrollBar::handle:vertical {    \n"
"    background: rgb(189, 147, 249);\n"
"    min-height: 25px;\n"
"    border-radius: 4px\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"     border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-bottom-left-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color:rgb(33, 33, 33)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_7 = QtWidgets.QFrame(self.frame)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_welcome = QtWidgets.QLabel(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_welcome.sizePolicy().hasHeightForWidth())
        self.label_welcome.setSizePolicy(sizePolicy)
        self.label_welcome.setStyleSheet("color:white;\n"
"background:rgb(255, 151, 99);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.label_welcome.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_welcome.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_welcome.setObjectName("label_welcome")
        self.horizontalLayout_3.addWidget(self.label_welcome)
        self.btn_logout = QtWidgets.QPushButton(self.frame_7)
        self.btn_logout.setStyleSheet("color:blue;\n"
"background-color:white;\n"
"padding:6px 20px;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"border-radius:5px;\n"
"")
        self.btn_logout.setAutoDefault(False)
        self.btn_logout.setDefault(False)
        self.btn_logout.setObjectName("btn_logout")
        self.horizontalLayout_3.addWidget(self.btn_logout)
        self.btn_settings = QtWidgets.QPushButton(self.frame_7)
        self.btn_settings.setStyleSheet("background:transparent")
        self.btn_settings.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../resources/images/settings-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_settings.setIcon(icon)
        self.btn_settings.setIconSize(QtCore.QSize(25, 25))
        self.btn_settings.setObjectName("btn_settings")
        self.horizontalLayout_3.addWidget(self.btn_settings)
        self.verticalLayout_3.addWidget(self.frame_7)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_12 = QtWidgets.QFrame(self.frame_2)
        self.frame_12.setMaximumSize(QtCore.QSize(350, 16777215))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.line_2 = QtWidgets.QFrame(self.frame_12)
        self.line_2.setStyleSheet("background-color:rgb(156, 156, 156);\n"
"border:1px inset black;")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_21.addWidget(self.line_2)
        self.label_17 = QtWidgets.QLabel(self.frame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setStyleSheet("color:black;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_17.setObjectName("label_17")
        self.verticalLayout_21.addWidget(self.label_17)
        self.line_4 = QtWidgets.QFrame(self.frame_12)
        self.line_4.setStyleSheet("background-color:rgb(156, 156, 156);\n"
"border:1px inset black;")
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_21.addWidget(self.line_4)
        self.frame_9 = QtWidgets.QFrame(self.frame_12)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(158, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.btn_reset_defaults = QtWidgets.QPushButton(self.frame_9)
        self.btn_reset_defaults.setStyleSheet("color:green;\n"
"background-color:white;\n"
"padding:6px 20px;\n"
"font: 11pt \"Microsoft YaHei\";\n"
"border-radius:5px;\n"
"")
        self.btn_reset_defaults.setObjectName("btn_reset_defaults")
        self.horizontalLayout_6.addWidget(self.btn_reset_defaults)
        self.verticalLayout_21.addWidget(self.frame_9)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.frame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_2.sizePolicy().hasHeightForWidth())
        self.scrollArea_2.setSizePolicy(sizePolicy)
        self.scrollArea_2.setStyleSheet("")
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 320, 1068))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.frame_16 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.frame_lower_rate_limit = QtWidgets.QFrame(self.frame_16)
        self.frame_lower_rate_limit.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_lower_rate_limit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_lower_rate_limit.setObjectName("frame_lower_rate_limit")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_lower_rate_limit)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.frame_lower_rate_limit)
        self.label_6.setStyleSheet("color:black;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_8.addWidget(self.label_6)
        self.param_lower_rate_limit = QtWidgets.QSpinBox(self.frame_lower_rate_limit)
        self.param_lower_rate_limit.setMinimumSize(QtCore.QSize(0, 35))
        self.param_lower_rate_limit.setStyleSheet("QSpinBox{\n"
"border:2px solid #55aaff;\n"
"border-radius:10px;\n"
"color:black;\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"}\n"
"QSpinBox::up-arrow { border-left:8px solid none;\n"
"                               border-right:  8px solid none; border-bottom: 7px solid #55aaff;  width: 0px; height: 0px;}\n"
"\n"
"QSpinBox::down-arrow { border-left: 8px solid none;\n"
"                               border-right: 8px solid none; border-top: 7px solid #55aaff; width: 0px; height: 0px; }")
        self.param_lower_rate_limit.setMinimum(30)
        self.param_lower_rate_limit.setMaximum(175)
        self.param_lower_rate_limit.setSingleStep(5)
        self.param_lower_rate_limit.setProperty("value", 60)
        self.param_lower_rate_limit.setObjectName("param_lower_rate_limit")
        self.verticalLayout_8.addWidget(self.param_lower_rate_limit)
        self.verticalLayout_22.addWidget(self.frame_lower_rate_limit)
        self.frame_upper_rate_limit = QtWidgets.QFrame(self.frame_16)
        self.frame_upper_rate_limit.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_upper_rate_limit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_upper_rate_limit.setObjectName("frame_upper_rate_limit")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_upper_rate_limit)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.frame_upper_rate_limit)
        self.label_5.setStyleSheet("color:black;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.param_upper_rate_limit = QtWidgets.QSpinBox(self.frame_upper_rate_limit)
        self.param_upper_rate_limit.setMinimumSize(QtCore.QSize(0, 35))
        self.param_upper_rate_limit.setStyleSheet("QSpinBox{\n"
"border:2px solid #55aaff;\n"
"border-radius:10px;\n"
"color:black;\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"}\n"
"QSpinBox::up-arrow { border-left:8px solid none;\n"
"                               border-right:  8px solid none; border-bottom: 7px solid #55aaff;  width: 0px; height: 0px;}\n"
"\n"
"QSpinBox::down-arrow { border-left: 8px solid none;\n"
"                               border-right: 8px solid none; border-top: 7px solid #55aaff; width: 0px; height: 0px; }")
        self.param_upper_rate_limit.setMinimum(50)
        self.param_upper_rate_limit.setMaximum(175)
        self.param_upper_rate_limit.setSingleStep(5)
        self.param_upper_rate_limit.setProperty("value", 120)
        self.param_upper_rate_limit.setObjectName("param_upper_rate_limit")
        self.verticalLayout_6.addWidget(self.param_upper_rate_limit)
        self.verticalLayout_22.addWidget(self.frame_upper_rate_limit)
        self.frame_maximum_sensor_rate = QtWidgets.QFrame(self.frame_16)
        self.frame_maximum_sensor_rate.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_maximum_sensor_rate.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_maximum_sensor_rate.setObjectName("frame_maximum_sensor_rate")
        self.verticalLayout_36 = QtWidgets.QVBoxLayout(self.frame_maximum_sensor_rate)
        self.verticalLayout_36.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.label_29 = QtWidgets.QLabel(self.frame_maximum_sensor_rate)
        self.label_29.setStyleSheet("color:black;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_29.setObjectName("label_29")
        self.verticalLayout_36.addWidget(self.label_29)
        self.param_maximum_sensor_rate = QtWidgets.QSpinBox(self.frame_maximum_sensor_rate)
        self.param_maximum_sensor_rate.setMinimumSize(QtCore.QSize(0, 35))
        self.param_maximum_sensor_rate.setStyleSheet("QSpinBox{\n"
"border:2px solid #55aaff;\n"
"border-radius:10px;\n"
"color:black;\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"}\n"
"QSpinBox::up-arrow { border-left:8px solid none;\n"
"                               border-right:  8px solid none; border-bottom: 7px solid #55aaff;  width: 0px; height: 0px;}\n"
"\n"
"QSpinBox::down-arrow { border-left: 8px solid none;\n"
"                               border-right: 8px solid none; border-top: 7px solid #55aaff; width: 0px; height: 0px; }")
        self.param_maximum_sensor_rate.setMinimum(50)
        self.param_maximum_sensor_rate.setMaximum(175)
        self.param_maximum_sensor_rate.setProperty("value", 120)
        self.param_maximum_sensor_rate.setObjectName("param_maximum_sensor_rate")
        self.verticalLayout_36.addWidget(self.param_maximum_sensor_rate)
        self.verticalLayout_22.addWidget(self.frame_maximum_sensor_rate)
        self.frame_fixed_av_delay = QtWidgets.QFrame(self.frame_16)
        self.frame_fixed_av_delay.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_fixed_av_delay.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_fixed_av_delay.setObjectName("frame_fixed_av_delay")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.frame_fixed_av_delay)
        self.verticalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_19 = QtWidgets.QLabel(self.frame_fixed_av_delay)
        self.label_19.setStyleSheet("color:black;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_19.setObjectName("label_19")
        self.verticalLayout_24.addWidget(self.label_19)
        self.param_fixed_av_delay = QtWidgets.QSpinBox(self.frame_fixed_av_delay)
        self.param_fixed_av_delay.setMinimumSize(QtCore.QSize(0, 35))
        self.param_fixed_av_delay.setStyleSheet("QSpinBox{\n"
"border:2px solid #55aaff;\n"
"border-radius:10px;\n"
"color:black;\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"}\n"
"QSpinBox::up-arrow { border-left:8px solid none;\n"
"                               border-right:  8px solid none; border-bottom: 7px solid #55aaff;  width: 0px; height: 0px;}\n"
"\n"
"QSpinBox::down-arrow { border-left: 8px solid none;\n"
"                               border-right: 8px solid none; border-top: 7px solid #55aaff; width: 0px; height: 0px; }")
        self.param_fixed_av_delay.setMinimum(70)
        self.param_fixed_av_delay.setMaximum(300)
        self.param_fixed_av_delay.setSingleStep(10)
        self.param_fixed_av_delay.setProperty("value", 150)
        self.param_fixed_av_delay.setObjectName("param_fixed_av_delay")
        self.verticalLayout_24.addWidget(self.param_fixed_av_delay)
        self.verticalLayout_22.addWidget(self.frame_fixed_av_delay)
        self.frame_atrial_amplitude = QtWidgets.QFrame(self.frame_16)
        self.frame_atrial_amplitude.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_atrial_amplitude.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_atrial_amplitude.setObjectName("frame_atrial_amplitude")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout(self.frame_atrial_amplitude)
        self.verticalLayout_35.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.label_27 = QtWidgets.QLabel(self.frame_atrial_amplitude)
        self.label_27.setStyleSheet("color:black;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_27.setObjectName("label_27")
        self.verticalLayout_35.addWidget(self.label_27)
        self.param_atrial_amplitude = QtWidgets.QDoubleSpinBox(self.frame_atrial_amplitude)
        self.param_atrial_amplitude.setMinimumSize(QtCore.QSize(0, 35))
        self.param_atrial_amplitude.setStyleSheet("QDoubleSpinBox{\n"
"border:2px solid #55aaff;\n"
"border-radius:10px;\n"
"color:black;\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"}\n"
"QDoubleSpinBox::up-arrow { border-left:8px solid none;\n"
"                               border-right:  8px solid none; border-bottom: 7px solid #55aaff;  width: 0px; height: 0px;}\n"
"\n"
"QDoubleSpinBox::down-arrow { border-left: 8px solid none;\n"
"                               border-right: 8px solid none; border-top: 7px solid #55aaff; width: 0px; height: 0px; }")
        self.param_atrial_amplitude.setMaximum(5.0)
        self.param_atrial_amplitude.setSingleStep(0.1)
        self.param_atrial_amplitude.setObjectName("param_atrial_amplitude")
        self.verticalLayout_35.addWidget(self.param_atrial_amplitude)
        self.verticalLayout_22.addWidget(self.frame_atrial_amplitude)
        self.frame_atrial_pulse_width = QtWidgets.QFrame(self.frame_16)
        self.frame_atrial_pulse_width.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_atrial_pulse_width.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_atrial_pulse_width.setObjectName("frame_atrial_pulse_width")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_atrial_pulse_width)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_23 = QtWidgets.QLabel(self.frame_atrial_pulse_width)
        self.label_23.setStyleSheet("color:black;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_23.setObjectName("label_23")
        self.verticalLayout_4.addWidget(self.label_23)
        self.param_atrial_pulse_width = QtWidgets.QDoubleSpinBox(self.frame_atrial_pulse_width)
        self.param_atrial_pulse_width.setMinimumSize(QtCore.QSize(0, 35))
        self.param_atrial_pulse_width.setStyleSheet("QDoubleSpinBox{\n"
"border:2px solid #55aaff;\n"
"border-radius:10px;\n"
"color:black;\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"}\n"
"QDoubleSpinBox::up-arrow { border-left:8px solid none;\n"
"                               border-right:  8px solid none; border-bottom: 7px solid #55aaff;  width: 0px; height: 0px;}\n"
"\n"
"QDoubleSpinBox::down-arrow { border-left: 8px solid none;\n"
"                               border-right: 8px solid none; border-top: 7px solid #55aaff; width: 0px; height: 0px; }")
        self.param_atrial_pulse_width.setMinimum(0.1)
        self.param_atrial_pulse_width.setMaximum(30.0)
        self.param_atrial_pulse_width.setSingleStep(0.1)
        self.param_atrial_pulse_width.setProperty("value", 1.0)
        self.param_atrial_pulse_width.setObjectName("param_atrial_pulse_width")
        self.verticalLayout_4.addWidget(self.param_atrial_pulse_width)
        self.verticalLayout_22.addWidget(self.frame_atrial_pulse_width)
        self.frame_atrial_sensitivity = QtWidgets.QFrame(self.frame_16)
        self.frame_atrial_sensitivity.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_atrial_sensitivity.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_atrial_sensitivity.setObjectName("frame_atrial_sensitivity")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout(self.frame_atrial_sensitivity)
        self.verticalLayout_34.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.label_26 = QtWidgets.QLabel(self.frame_atrial_sensitivity)
        self.label_26.setStyleSheet("color:black;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_26.setObjectName("label_26")
        self.verticalLayout_34.addWidget(self.label_26)
        self.param_atrial_sensitivity = QtWidgets.QDoubleSpinBox(self.frame_atrial_sensitivity)
        self.param_atrial_sensitivity.setMinimumSize(QtCore.QSize(0, 35))
        self.param_atrial_sensitivity.setStyleSheet("QDoubleSpinBox{\n"
"border:2px solid #55aaff;\n"
"border-radius:10px;\n"
"color:black;\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"}\n"
"QDoubleSpinBox::up-arrow { border-left:8px solid none;\n"
"                               border-right:  8px solid none; border-bottom: 7px solid #55aaff;  width: 0px; height: 0px;}\n"
"\n"
"QDoubleSpinBox::down-arrow { border-left: 8px solid none;\n"
"                               border-right: 8px solid none; border-top: 7px solid #55aaff; width: 0px; height: 0px; }")
        self.param_atrial_sensitivity.setMinimum(0.5)
        self.param_atrial_sensitivity.setMaximum(10.0)
        self.param_atrial_sensitivity.setSingleStep(0.5)
        self.param_atrial_sensitivity.setProperty("value", 1.0)
        self.param_atrial_sensitivity.setObjectName("param_atrial_sensitivity")
        self.verticalLayout_34.addWidget(self.param_atrial_sensitivity)
        self.verticalLayout_22.addWidget(self.frame_atrial_sensitivity)
        self.frame_ventricular_amplitude = QtWidgets.QFrame(self.frame_16)
        self.frame_ventricular_amplitude.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_ventricular_amplitude.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_ventricular_amplitude.setObjectName("frame_ventricular_amplitude")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.frame_ventricular_amplitude)
        self.verticalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.label_24 = QtWidgets.QLabel(self.frame_ventricular_amplitude)
        self.label_24.setStyleSheet("color:black;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_24.setObjectName("label_24")
        self.verticalLayout_32.addWidget(self.label_24)
        self.param_ventricular_amplitude = QtWidgets.QDoubleSpinBox(self.frame_ventricular_amplitude)
        self.param_ventricular_amplitude.setMinimumSize(QtCore.QSize(0, 35))
        self.param_ventricular_amplitude.setStyleSheet("QDoubleSpinBox{\n"
"border:2px solid #55aaff;\n"
"border-radius:10px;\n"
"color:black;\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"}\n"
"QDoubleSpinBox::up-arrow { border-left:8px solid none;\n"
"                               border-right:  8px solid none; border-bottom: 7px solid #55aaff;  width: 0px; height: 0px;}\n"
"\n"
"QDoubleSpinBox::down-arrow { border-left: 8px solid none;\n"
"                               border-right: 8px solid none; border-top: 7px solid #55aaff; width: 0px; height: 0px; }")
        self.param_ventricular_amplitude.setMinimum(0.0)
        self.param_ventricular_amplitude.setMaximum(5.0)
        self.param_ventricular_amplitude.setSingleStep(0.1)
        self.param_ventricular_amplitude.setProperty("value", 5.0)
        self.param_ventricular_amplitude.setObjectName("param_ventricular_amplitude")
        self.verticalLayout_32.addWidget(self.param_ventricular_amplitude)
        self.verticalLayout_22.addWidget(self.frame_ventricular_amplitude)
        self.frame_ventricular_pulse_width = QtWidgets.QFrame(self.frame_16)
        self.frame_ventricular_pulse_width.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_ventricular_pulse_width.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_ventricular_pulse_width.setObjectName("frame_ventricular_pulse_width")
        self.verticalLayout_40 = QtWidgets.QVBoxLayout(self.frame_ventricular_pulse_width)
        self.verticalLayout_40.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_40.setObjectName("verticalLayout_40")
        self.label_32 = QtWidgets.QLabel(self.frame_ventricular_pulse_width)
        self.label_32.setStyleSheet("color:black;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_32.setObjectName("label_32")
        self.verticalLayout_40.addWidget(self.label_32)
        self.param_ventricular_pulse_width = QtWidgets.QDoubleSpinBox(self.frame_ventricular_pulse_width)
        self.param_ventricular_pulse_width.setMinimumSize(QtCore.QSize(0, 35))
        self.param_ventricular_pulse_width.setStyleSheet("QDoubleSpinBox{\n"
"border:2px solid #55aaff;\n"
"border-radius:10px;\n"
"color:black;\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"}\n"
"QDoubleSpinBox::up-arrow { border-left:8px solid none;\n"
"                               border-right:  8px solid none; border-bottom: 7px solid #55aaff;  width: 0px; height: 0px;}\n"
"\n"
"QDoubleSpinBox::down-arrow { border-left: 8px solid none;\n"
"                               border-right: 8px solid none; border-top: 7px solid #55aaff; width: 0px; height: 0px; }")
        self.param_ventricular_pulse_width.setMinimum(0.1)
        self.param_ventricular_pulse_width.setMaximum(30.0)
        self.param_ventricular_pulse_width.setSingleStep(0.1)
        self.param_ventricular_pulse_width.setProperty("value", 1.0)
        self.param_ventricular_pulse_width.setObjectName("param_ventricular_pulse_width")
        self.verticalLayout_40.addWidget(self.param_ventricular_pulse_width)
        self.verticalLayout_22.addWidget(self.frame_ventricular_pulse_width)
        self.frame_ventricular_sensitivity = QtWidgets.QFrame(self.frame_16)
        self.frame_ventricular_sensitivity.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_ventricular_sensitivity.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_ventricular_sensitivity.setObjectName("frame_ventricular_sensitivity")
        self.verticalLayout_39 = QtWidgets.QVBoxLayout(self.frame_ventricular_sensitivity)
        self.verticalLayout_39.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.label_31 = QtWidgets.QLabel(self.frame_ventricular_sensitivity)
        self.label_31.setStyleSheet("color:black;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_31.setObjectName("label_31")
        self.verticalLayout_39.addWidget(self.label_31)
        self.param_ventricular_sensitivity = QtWidgets.QDoubleSpinBox(self.frame_ventricular_sensitivity)
        self.param_ventricular_sensitivity.setMinimumSize(QtCore.QSize(0, 35))
        self.param_ventricular_sensitivity.setStyleSheet("QDoubleSpinBox{\n"
"border:2px solid #55aaff;\n"
"border-radius:10px;\n"
"color:black;\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"}\n"
"QDoubleSpinBox::up-arrow { border-left:8px solid none;\n"
"                               border-right:  8px solid none; border-bottom: 7px solid #55aaff;  width: 0px; height: 0px;}\n"
"\n"
"QDoubleSpinBox::down-arrow { border-left: 8px solid none;\n"
"                               border-right: 8px solid none; border-top: 7px solid #55aaff; width: 0px; height: 0px; }")
        self.param_ventricular_sensitivity.setMinimum(0.5)
        self.param_ventricular_sensitivity.setMaximum(10.0)
        self.param_ventricular_sensitivity.setSingleStep(0.5)
        self.param_ventricular_sensitivity.setProperty("value", 2.5)
        self.param_ventricular_sensitivity.setObjectName("param_ventricular_sensitivity")
        self.verticalLayout_39.addWidget(self.param_ventricular_sensitivity)
        self.verticalLayout_22.addWidget(self.frame_ventricular_sensitivity)
        self.frame_arp = QtWidgets.QFrame(self.frame_16)
        self.frame_arp.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_arp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_arp.setObjectName("frame_arp")
        self.verticalLayout_38 = QtWidgets.QVBoxLayout(self.frame_arp)
        self.verticalLayout_38.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.label_30 = QtWidgets.QLabel(self.frame_arp)
        self.label_30.setStyleSheet("color:black;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_30.setObjectName("label_30")
        self.verticalLayout_38.addWidget(self.label_30)
        self.param_arp = QtWidgets.QSpinBox(self.frame_arp)
        self.param_arp.setMinimumSize(QtCore.QSize(0, 35))
        self.param_arp.setStyleSheet("QSpinBox{\n"
"border:2px solid #55aaff;\n"
"border-radius:10px;\n"
"color:black;\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"}\n"
"QSpinBox::up-arrow { border-left:8px solid none;\n"
"                               border-right:  8px solid none; border-bottom: 7px solid #55aaff;  width: 0px; height: 0px;}\n"
"\n"
"QSpinBox::down-arrow { border-left: 8px solid none;\n"
"                               border-right: 8px solid none; border-top: 7px solid #55aaff; width: 0px; height: 0px; }")
        self.param_arp.setMinimum(150)
        self.param_arp.setMaximum(500)
        self.param_arp.setSingleStep(10)
        self.param_arp.setProperty("value", 250)
        self.param_arp.setObjectName("param_arp")
        self.verticalLayout_38.addWidget(self.param_arp)
        self.verticalLayout_22.addWidget(self.frame_arp)
        self.frame_vrp = QtWidgets.QFrame(self.frame_16)
        self.frame_vrp.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_vrp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_vrp.setObjectName("frame_vrp")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.frame_vrp)
        self.verticalLayout_33.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.label_25 = QtWidgets.QLabel(self.frame_vrp)
        self.label_25.setStyleSheet("color:black;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_25.setObjectName("label_25")
        self.verticalLayout_33.addWidget(self.label_25)
        self.param_vrp = QtWidgets.QSpinBox(self.frame_vrp)
        self.param_vrp.setMinimumSize(QtCore.QSize(0, 35))
        self.param_vrp.setStyleSheet("QSpinBox{\n"
"border:2px solid #55aaff;\n"
"border-radius:10px;\n"
"color:black;\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"}\n"
"QSpinBox::up-arrow { border-left:8px solid none;\n"
"                               border-right:  8px solid none; border-bottom: 7px solid #55aaff;  width: 0px; height: 0px;}\n"
"\n"
"QSpinBox::down-arrow { border-left: 8px solid none;\n"
"                               border-right: 8px solid none; border-top: 7px solid #55aaff; width: 0px; height: 0px; }")
        self.param_vrp.setMinimum(150)
        self.param_vrp.setMaximum(500)
        self.param_vrp.setSingleStep(10)
        self.param_vrp.setProperty("value", 320)
        self.param_vrp.setObjectName("param_vrp")
        self.verticalLayout_33.addWidget(self.param_vrp)
        self.verticalLayout_22.addWidget(self.frame_vrp)
        self.frame_pvarp = QtWidgets.QFrame(self.frame_16)
        self.frame_pvarp.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pvarp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pvarp.setObjectName("frame_pvarp")
        self.verticalLayout_37 = QtWidgets.QVBoxLayout(self.frame_pvarp)
        self.verticalLayout_37.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.label_28 = QtWidgets.QLabel(self.frame_pvarp)
        self.label_28.setStyleSheet("color:black;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_28.setObjectName("label_28")
        self.verticalLayout_37.addWidget(self.label_28)
        self.param_pvarp = QtWidgets.QSpinBox(self.frame_pvarp)
        self.param_pvarp.setMinimumSize(QtCore.QSize(0, 35))
        self.param_pvarp.setStyleSheet("QSpinBox{\n"
"border:2px solid #55aaff;\n"
"border-radius:10px;\n"
"color:black;\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"}\n"
"QSpinBox::up-arrow { border-left:8px solid none;\n"
"                               border-right:  8px solid none; border-bottom: 7px solid #55aaff;  width: 0px; height: 0px;}\n"
"\n"
"QSpinBox::down-arrow { border-left: 8px solid none;\n"
"                               border-right: 8px solid none; border-top: 7px solid #55aaff; width: 0px; height: 0px; }")
        self.param_pvarp.setMinimum(150)
        self.param_pvarp.setMaximum(500)
        self.param_pvarp.setSingleStep(10)
        self.param_pvarp.setProperty("value", 250)
        self.param_pvarp.setObjectName("param_pvarp")
        self.verticalLayout_37.addWidget(self.param_pvarp)
        self.verticalLayout_22.addWidget(self.frame_pvarp)
        self.frame_activity_threshold = QtWidgets.QFrame(self.frame_16)
        self.frame_activity_threshold.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_activity_threshold.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_activity_threshold.setObjectName("frame_activity_threshold")
        self.verticalLayout_41 = QtWidgets.QVBoxLayout(self.frame_activity_threshold)
        self.verticalLayout_41.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_41.setObjectName("verticalLayout_41")
        self.label_33 = QtWidgets.QLabel(self.frame_activity_threshold)
        self.label_33.setStyleSheet("color:black;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_33.setObjectName("label_33")
        self.verticalLayout_41.addWidget(self.label_33)
        self.param_activity_threshold = QtWidgets.QComboBox(self.frame_activity_threshold)
        self.param_activity_threshold.setMinimumSize(QtCore.QSize(103, 35))
        self.param_activity_threshold.setStyleSheet("QComboBox {\n"
"    border: 2px solid  #55aaff;\n"
"    border-radius: 10px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"color:black;\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"  border: 2px inset gray;\n"
"  background: rgb(33, 33, 33);\n"
"  selection-background-color: black;\n"
"selection-color:#55aaff;\n"
"color:black;\n"
"border-radius:none;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"    border-left-width: 1px;\n"
"    border-left-color:  #55aaff;\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"border-left: 7px solid none;\n"
"                               border-right: 7px solid none; border-top: 5px solid #55aaff; width: 0px; height: 0px;\n"
"}\n"
"\n"
"QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n"
"    top: 1px;\n"
"    left: 1px;\n"
"}\n"
"QComboBox::item {\n"
"    border-top: 4;\n"
"    border-left: 4;\n"
"    border-bottom: 4;\n"
"    border-right: 4;\n"
"    background-color: #C87020;\n"
"    color: rgb(200, 112, 32);\n"
"}")
        self.param_activity_threshold.setObjectName("param_activity_threshold")
        self.param_activity_threshold.addItem("")
        self.param_activity_threshold.addItem("")
        self.param_activity_threshold.addItem("")
        self.param_activity_threshold.addItem("")
        self.param_activity_threshold.addItem("")
        self.param_activity_threshold.addItem("")
        self.param_activity_threshold.addItem("")
        self.verticalLayout_41.addWidget(self.param_activity_threshold)
        self.verticalLayout_22.addWidget(self.frame_activity_threshold)
        self.frame_reaction_time = QtWidgets.QFrame(self.frame_16)
        self.frame_reaction_time.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_reaction_time.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_reaction_time.setObjectName("frame_reaction_time")
        self.verticalLayout_42 = QtWidgets.QVBoxLayout(self.frame_reaction_time)
        self.verticalLayout_42.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_42.setObjectName("verticalLayout_42")
        self.label_34 = QtWidgets.QLabel(self.frame_reaction_time)
        self.label_34.setStyleSheet("color:black;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_34.setObjectName("label_34")
        self.verticalLayout_42.addWidget(self.label_34)
        self.param_reaction_time = QtWidgets.QSpinBox(self.frame_reaction_time)
        self.param_reaction_time.setMinimumSize(QtCore.QSize(0, 35))
        self.param_reaction_time.setStyleSheet("QSpinBox{\n"
"border:2px solid #55aaff;\n"
"border-radius:10px;\n"
"color:black;\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"}\n"
"QSpinBox::up-arrow { border-left:8px solid none;\n"
"                               border-right:  8px solid none; border-bottom: 7px solid #55aaff;  width: 0px; height: 0px;}\n"
"\n"
"QSpinBox::down-arrow { border-left: 8px solid none;\n"
"                               border-right: 8px solid none; border-top: 7px solid #55aaff; width: 0px; height: 0px; }")
        self.param_reaction_time.setMinimum(10)
        self.param_reaction_time.setMaximum(50)
        self.param_reaction_time.setSingleStep(10)
        self.param_reaction_time.setProperty("value", 30)
        self.param_reaction_time.setObjectName("param_reaction_time")
        self.verticalLayout_42.addWidget(self.param_reaction_time)
        self.verticalLayout_22.addWidget(self.frame_reaction_time)
        self.frame_response_factor = QtWidgets.QFrame(self.frame_16)
        self.frame_response_factor.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_response_factor.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_response_factor.setObjectName("frame_response_factor")
        self.verticalLayout_43 = QtWidgets.QVBoxLayout(self.frame_response_factor)
        self.verticalLayout_43.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_43.setObjectName("verticalLayout_43")
        self.label_35 = QtWidgets.QLabel(self.frame_response_factor)
        self.label_35.setStyleSheet("color:black;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_35.setObjectName("label_35")
        self.verticalLayout_43.addWidget(self.label_35)
        self.param_response_factor = QtWidgets.QSpinBox(self.frame_response_factor)
        self.param_response_factor.setMinimumSize(QtCore.QSize(0, 35))
        self.param_response_factor.setStyleSheet("QSpinBox{\n"
"border:2px solid #55aaff;\n"
"border-radius:10px;\n"
"color:black;\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"}\n"
"QSpinBox::up-arrow { border-left:8px solid none;\n"
"                               border-right:  8px solid none; border-bottom: 7px solid #55aaff;  width: 0px; height: 0px;}\n"
"\n"
"QSpinBox::down-arrow { border-left: 8px solid none;\n"
"                               border-right: 8px solid none; border-top: 7px solid #55aaff; width: 0px; height: 0px; }")
        self.param_response_factor.setMinimum(1)
        self.param_response_factor.setMaximum(16)
        self.param_response_factor.setSingleStep(1)
        self.param_response_factor.setProperty("value", 8)
        self.param_response_factor.setObjectName("param_response_factor")
        self.verticalLayout_43.addWidget(self.param_response_factor)
        self.verticalLayout_22.addWidget(self.frame_response_factor)
        self.frame_recovery_time = QtWidgets.QFrame(self.frame_16)
        self.frame_recovery_time.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_recovery_time.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_recovery_time.setObjectName("frame_recovery_time")
        self.verticalLayout_44 = QtWidgets.QVBoxLayout(self.frame_recovery_time)
        self.verticalLayout_44.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_44.setObjectName("verticalLayout_44")
        self.label_36 = QtWidgets.QLabel(self.frame_recovery_time)
        self.label_36.setStyleSheet("color:black;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_36.setObjectName("label_36")
        self.verticalLayout_44.addWidget(self.label_36)
        self.param_recovery_time = QtWidgets.QSpinBox(self.frame_recovery_time)
        self.param_recovery_time.setMinimumSize(QtCore.QSize(0, 35))
        self.param_recovery_time.setStyleSheet("QSpinBox{\n"
"border:2px solid #55aaff;\n"
"border-radius:10px;\n"
"color:black;\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"}\n"
"QSpinBox::up-arrow { border-left:8px solid none;\n"
"                               border-right:  8px solid none; border-bottom: 7px solid #55aaff;  width: 0px; height: 0px;}\n"
"\n"
"QSpinBox::down-arrow { border-left: 8px solid none;\n"
"                               border-right: 8px solid none; border-top: 7px solid #55aaff; width: 0px; height: 0px; }")
        self.param_recovery_time.setMinimum(2)
        self.param_recovery_time.setMaximum(16)
        self.param_recovery_time.setSingleStep(1)
        self.param_recovery_time.setProperty("value", 5)
        self.param_recovery_time.setObjectName("param_recovery_time")
        self.verticalLayout_44.addWidget(self.param_recovery_time)
        self.verticalLayout_22.addWidget(self.frame_recovery_time)
        self.verticalLayout_29.addWidget(self.frame_16)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_21.addWidget(self.scrollArea_2)
        self.frame_6 = QtWidgets.QFrame(self.frame_12)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(38, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.btn_update_params = QtWidgets.QPushButton(self.frame_6)
        self.btn_update_params.setStyleSheet("color:black;\n"
"background-color:rgb(85, 170, 255);\n"
"padding:6px 20px;\n"
"font: 11pt \"Microsoft YaHei\";\n"
"border-radius:5px;\n"
"")
        self.btn_update_params.setObjectName("btn_update_params")
        self.horizontalLayout_4.addWidget(self.btn_update_params)
        self.btn_transmit_data = QtWidgets.QPushButton(self.frame_6)
        self.btn_transmit_data.setStyleSheet("color:white;\n"
"background-color:rgb(255, 0, 0);\n"
"padding:6px 20px;\n"
"font: 11pt \"Microsoft YaHei\";\n"
"border-radius:5px;\n"
"")
        self.btn_transmit_data.setObjectName("btn_transmit_data")
        self.horizontalLayout_4.addWidget(self.btn_transmit_data)
        self.verticalLayout_21.addWidget(self.frame_6)
        self.label_14 = QtWidgets.QLabel(self.frame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setStyleSheet("color:black;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_14.setObjectName("label_14")
        self.verticalLayout_21.addWidget(self.label_14)
        self.frame_13 = QtWidgets.QFrame(self.frame_12)
        self.frame_13.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_13.setStyleSheet("color:black;")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_13)
        self.gridLayout.setObjectName("gridLayout")
        self.mode_AOOR = QtWidgets.QRadioButton(self.frame_13)
        self.mode_AOOR.setStyleSheet("color:black;")
        self.mode_AOOR.setObjectName("mode_AOOR")
        self.gridLayout.addWidget(self.mode_AOOR, 1, 1, 1, 1)
        self.mode_AOO = QtWidgets.QRadioButton(self.frame_13)
        self.mode_AOO.setStyleSheet("color:black;")
        self.mode_AOO.setObjectName("mode_AOO")
        self.gridLayout.addWidget(self.mode_AOO, 1, 0, 1, 1)
        self.mode_VOO = QtWidgets.QRadioButton(self.frame_13)
        self.mode_VOO.setStyleSheet("color:black;")
        self.mode_VOO.setObjectName("mode_VOO")
        self.gridLayout.addWidget(self.mode_VOO, 2, 0, 1, 1)
        self.mode_AAI = QtWidgets.QRadioButton(self.frame_13)
        self.mode_AAI.setStyleSheet("color:black;")
        self.mode_AAI.setObjectName("mode_AAI")
        self.gridLayout.addWidget(self.mode_AAI, 3, 0, 1, 1)
        self.mode_VVI = QtWidgets.QRadioButton(self.frame_13)
        self.mode_VVI.setStyleSheet("color:black;")
        self.mode_VVI.setObjectName("mode_VVI")
        self.gridLayout.addWidget(self.mode_VVI, 4, 0, 1, 1)
        self.mode_VVIR = QtWidgets.QRadioButton(self.frame_13)
        self.mode_VVIR.setStyleSheet("color:black;")
        self.mode_VVIR.setObjectName("mode_VVIR")
        self.gridLayout.addWidget(self.mode_VVIR, 4, 1, 1, 1)
        self.mode_AAIR = QtWidgets.QRadioButton(self.frame_13)
        self.mode_AAIR.setStyleSheet("color:black;")
        self.mode_AAIR.setObjectName("mode_AAIR")
        self.gridLayout.addWidget(self.mode_AAIR, 3, 1, 1, 1)
        self.mode_VOOR = QtWidgets.QRadioButton(self.frame_13)
        self.mode_VOOR.setStyleSheet("color:black;")
        self.mode_VOOR.setObjectName("mode_VOOR")
        self.gridLayout.addWidget(self.mode_VOOR, 2, 1, 1, 1)
        self.mode_DOO = QtWidgets.QRadioButton(self.frame_13)
        self.mode_DOO.setStyleSheet("color:black;")
        self.mode_DOO.setObjectName("mode_DOO")
        self.gridLayout.addWidget(self.mode_DOO, 5, 0, 1, 1)
        self.mode_DOOR = QtWidgets.QRadioButton(self.frame_13)
        self.mode_DOOR.setStyleSheet("color:black;")
        self.mode_DOOR.setObjectName("mode_DOOR")
        self.gridLayout.addWidget(self.mode_DOOR, 5, 1, 1, 1)
        self.verticalLayout_21.addWidget(self.frame_13)
        self.horizontalLayout.addWidget(self.frame_12)
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setStyleSheet("background:rgb(255, 255, 255)")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.groupBox = QtWidgets.QGroupBox(self.frame_5)
        self.groupBox.setGeometry(QtCore.QRect(30, 20, 564, 544))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setStyleSheet("color:rgb(0, 0, 0)")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_plots_checks = QtWidgets.QFrame(self.groupBox)
        self.frame_plots_checks.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_plots_checks.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_plots_checks.setObjectName("frame_plots_checks")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_plots_checks)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(166, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.radioButton_ventricular = QtWidgets.QRadioButton(self.frame_plots_checks)
        self.radioButton_ventricular.setObjectName("radioButton_ventricular")
        self.horizontalLayout_5.addWidget(self.radioButton_ventricular)
        self.radioButton_atrial = QtWidgets.QRadioButton(self.frame_plots_checks)
        self.radioButton_atrial.setObjectName("radioButton_atrial")
        self.horizontalLayout_5.addWidget(self.radioButton_atrial)
        self.radioButton_both = QtWidgets.QRadioButton(self.frame_plots_checks)
        self.radioButton_both.setObjectName("radioButton_both")
        self.horizontalLayout_5.addWidget(self.radioButton_both)
        spacerItem3 = QtWidgets.QSpacerItem(166, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.verticalLayout_2.addWidget(self.frame_plots_checks)
        self.frame_atrial = QtWidgets.QFrame(self.groupBox)
        self.frame_atrial.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_atrial.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_atrial.setObjectName("frame_atrial")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_atrial)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(526, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_2.addWidget(self.frame_atrial)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.line_5 = QtWidgets.QFrame(self.groupBox)
        self.line_5.setStyleSheet("background-color:rgb(156, 156, 156);\n"
"border:1px inset black;")
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_2.addWidget(self.line_5)
        self.ventricular_plots = PlotWidget(self.groupBox)
        self.ventricular_plots.setObjectName("ventricular_plots")
        self.verticalLayout_2.addWidget(self.ventricular_plots)
        self.frame_ventricular = QtWidgets.QFrame(self.groupBox)
        self.frame_ventricular.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_ventricular.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_ventricular.setObjectName("frame_ventricular")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_ventricular)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem5 = QtWidgets.QSpacerItem(526, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.verticalLayout_2.addWidget(self.frame_ventricular)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.atrial_plots = PlotWidget(self.groupBox)
        self.atrial_plots.setStyleSheet("color:black;")
        self.atrial_plots.setObjectName("atrial_plots")
        self.verticalLayout_2.addWidget(self.atrial_plots)
        self.line_6 = QtWidgets.QFrame(self.groupBox)
        self.line_6.setStyleSheet("background-color:rgb(156, 156, 156);\n"
"border:1px inset black;")
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_2.addWidget(self.line_6)
        self.horizontalLayout.addWidget(self.frame_5)
        self.verticalLayout.addWidget(self.frame_2)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setStyleSheet("background-color:rgb(156, 156, 156);\n"
"border:1px inset black;")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        DCMInterface.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(DCMInterface)
        self.statusBar.setStyleSheet("background-color:rgb(33, 33, 33)")
        self.statusBar.setObjectName("statusBar")
        DCMInterface.setStatusBar(self.statusBar)

        self.retranslateUi(DCMInterface)
        QtCore.QMetaObject.connectSlotsByName(DCMInterface)

    def retranslateUi(self, DCMInterface):
        _translate = QtCore.QCoreApplication.translate
        DCMInterface.setWindowTitle(_translate("DCMInterface", "Pacemaker: Device Controller Monitor"))
        self.label_welcome.setText(_translate("DCMInterface", "Welcome, "))
        self.btn_logout.setText(_translate("DCMInterface", "Log Out"))
        self.label_17.setText(_translate("DCMInterface", "Programmable Parameters"))
        self.btn_reset_defaults.setText(_translate("DCMInterface", "Reset Defaults"))
        self.frame_16.setStyleSheet(_translate("DCMInterface", "color:black;\n"
"font: 10pt \"MS Shell Dlg 2\";"))
        self.label_6.setText(_translate("DCMInterface", "Lower Rate Limit (ppm)"))
        self.label_5.setText(_translate("DCMInterface", "Upper Rate Limit (ppm)"))
        self.label_29.setText(_translate("DCMInterface", "Maximum Sensor Rate (ppm)"))
        self.label_19.setText(_translate("DCMInterface", "Fixed AV Delay (ms)"))
        self.label_27.setText(_translate("DCMInterface", "Atrial Amplitude (V)"))
        self.label_23.setText(_translate("DCMInterface", "Atrial Pulse Width (ms)"))
        self.label_26.setText(_translate("DCMInterface", "Atrial Sensitivity (mV)"))
        self.label_24.setText(_translate("DCMInterface", "Ventricular Amplitude (V)"))
        self.frame_ventricular_pulse_width.setStyleSheet(_translate("DCMInterface", "QDoubleSpinBox{\n"
"border:2px solid #55aaff;\n"
"border-radius:10px;\n"
"color:black;\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"}\n"
"QDoubleSpinBox::up-arrow { border-left:8px solid none;\n"
"                               border-right:  8px solid none; border-bottom: 7px solid #55aaff;  width: 0px; height: 0px;}\n"
"\n"
"QDoubleSpinBox::down-arrow { border-left: 8px solid none;\n"
"                               border-right: 8px solid none; border-top: 7px solid #55aaff; width: 0px; height: 0px; }"))
        self.label_32.setText(_translate("DCMInterface", "Ventricular Pulse Width (ms)"))
        self.label_31.setText(_translate("DCMInterface", "Ventricular Sensitivity (mV)"))
        self.label_30.setText(_translate("DCMInterface", "ARP (ms)"))
        self.label_25.setText(_translate("DCMInterface", "VRP (ms)"))
        self.label_28.setText(_translate("DCMInterface", "PVARP (ms)"))
        self.label_33.setText(_translate("DCMInterface", "Activity Threshold"))
        self.param_activity_threshold.setCurrentText(_translate("DCMInterface", "V-Low"))
        self.param_activity_threshold.setItemText(0, _translate("DCMInterface", "V-Low"))
        self.param_activity_threshold.setItemText(1, _translate("DCMInterface", "Low"))
        self.param_activity_threshold.setItemText(2, _translate("DCMInterface", "Med-Low"))
        self.param_activity_threshold.setItemText(3, _translate("DCMInterface", "Med"))
        self.param_activity_threshold.setItemText(4, _translate("DCMInterface", "Med-High"))
        self.param_activity_threshold.setItemText(5, _translate("DCMInterface", "High"))
        self.param_activity_threshold.setItemText(6, _translate("DCMInterface", "V-High"))
        self.label_34.setText(_translate("DCMInterface", "Reaction Time (sec)"))
        self.label_35.setText(_translate("DCMInterface", "Response Factor"))
        self.label_36.setText(_translate("DCMInterface", "Recovery Time (min)"))
        self.btn_update_params.setText(_translate("DCMInterface", "Update Params"))
        self.btn_transmit_data.setText(_translate("DCMInterface", "Transmit Data"))
        self.label_14.setText(_translate("DCMInterface", "Pacing Mode"))
        self.mode_AOOR.setText(_translate("DCMInterface", "AOOR"))
        self.mode_AOO.setText(_translate("DCMInterface", "AOO"))
        self.mode_VOO.setText(_translate("DCMInterface", "VOO"))
        self.mode_AAI.setText(_translate("DCMInterface", "AAI"))
        self.mode_VVI.setText(_translate("DCMInterface", "VVI"))
        self.mode_VVIR.setText(_translate("DCMInterface", "VVIR"))
        self.mode_AAIR.setText(_translate("DCMInterface", "AAIR"))
        self.mode_VOOR.setText(_translate("DCMInterface", "VOOR"))
        self.mode_DOO.setText(_translate("DCMInterface", "DOO"))
        self.mode_DOOR.setText(_translate("DCMInterface", "DOOR"))
        self.groupBox.setTitle(_translate("DCMInterface", "Electrogram"))
        self.radioButton_ventricular.setText(_translate("DCMInterface", "Ventricular"))
        self.radioButton_atrial.setText(_translate("DCMInterface", "Atrial"))
        self.radioButton_both.setText(_translate("DCMInterface", "Both"))
        self.label.setText(_translate("DCMInterface", "Ventricular"))
        self.label_2.setText(_translate("DCMInterface", "Atrial"))
from pyqtgraph import PlotWidget
